// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: board.proto

package mech.mania.engine.domain.model;

public final class BoardProtos {
  private BoardProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BoardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:board.Board)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 rows = 1;</code>
     * @return The rows.
     */
    int getRows();

    /**
     * <code>int32 columns = 2;</code>
     * @return The columns.
     */
    int getColumns();

    /**
     * <pre>
     * Protos only have 1D lists (row-major)
     * </pre>
     *
     * <code>repeated .board.Tile grid = 3;</code>
     */
    java.util.List<Tile>
        getGridList();
    /**
     * <pre>
     * Protos only have 1D lists (row-major)
     * </pre>
     *
     * <code>repeated .board.Tile grid = 3;</code>
     */
    Tile getGrid(int index);
    /**
     * <pre>
     * Protos only have 1D lists (row-major)
     * </pre>
     *
     * <code>repeated .board.Tile grid = 3;</code>
     */
    int getGridCount();
    /**
     * <pre>
     * Protos only have 1D lists (row-major)
     * </pre>
     *
     * <code>repeated .board.Tile grid = 3;</code>
     */
    java.util.List<? extends TileOrBuilder>
        getGridOrBuilderList();
    /**
     * <pre>
     * Protos only have 1D lists (row-major)
     * </pre>
     *
     * <code>repeated .board.Tile grid = 3;</code>
     */
    TileOrBuilder getGridOrBuilder(
        int index);

    /**
     * <code>repeated .character.Position portals = 4;</code>
     */
    java.util.List<CharacterProtos.Position>
        getPortalsList();
    /**
     * <code>repeated .character.Position portals = 4;</code>
     */
    CharacterProtos.Position getPortals(int index);
    /**
     * <code>repeated .character.Position portals = 4;</code>
     */
    int getPortalsCount();
    /**
     * <code>repeated .character.Position portals = 4;</code>
     */
    java.util.List<? extends CharacterProtos.PositionOrBuilder>
        getPortalsOrBuilderList();
    /**
     * <code>repeated .character.Position portals = 4;</code>
     */
    CharacterProtos.PositionOrBuilder getPortalsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code board.Board}
   */
  public static final class Board extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:board.Board)
      BoardOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Board.newBuilder() to construct.
    private Board(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Board() {
      grid_ = java.util.Collections.emptyList();
      portals_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Board();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Board(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              rows_ = input.readInt32();
              break;
            }
            case 16: {

              columns_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                grid_ = new java.util.ArrayList<Tile>();
                mutable_bitField0_ |= 0x00000001;
              }
              grid_.add(
                  input.readMessage(Tile.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                portals_ = new java.util.ArrayList<CharacterProtos.Position>();
                mutable_bitField0_ |= 0x00000002;
              }
              portals_.add(
                  input.readMessage(CharacterProtos.Position.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          grid_ = java.util.Collections.unmodifiableList(grid_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          portals_ = java.util.Collections.unmodifiableList(portals_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BoardProtos.internal_static_board_Board_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BoardProtos.internal_static_board_Board_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Board.class, Builder.class);
    }

    public static final int ROWS_FIELD_NUMBER = 1;
    private int rows_;
    /**
     * <code>int32 rows = 1;</code>
     * @return The rows.
     */
    @Override
    public int getRows() {
      return rows_;
    }

    public static final int COLUMNS_FIELD_NUMBER = 2;
    private int columns_;
    /**
     * <code>int32 columns = 2;</code>
     * @return The columns.
     */
    @Override
    public int getColumns() {
      return columns_;
    }

    public static final int GRID_FIELD_NUMBER = 3;
    private java.util.List<Tile> grid_;
    /**
     * <pre>
     * Protos only have 1D lists (row-major)
     * </pre>
     *
     * <code>repeated .board.Tile grid = 3;</code>
     */
    @Override
    public java.util.List<Tile> getGridList() {
      return grid_;
    }
    /**
     * <pre>
     * Protos only have 1D lists (row-major)
     * </pre>
     *
     * <code>repeated .board.Tile grid = 3;</code>
     */
    @Override
    public java.util.List<? extends TileOrBuilder>
        getGridOrBuilderList() {
      return grid_;
    }
    /**
     * <pre>
     * Protos only have 1D lists (row-major)
     * </pre>
     *
     * <code>repeated .board.Tile grid = 3;</code>
     */
    @Override
    public int getGridCount() {
      return grid_.size();
    }
    /**
     * <pre>
     * Protos only have 1D lists (row-major)
     * </pre>
     *
     * <code>repeated .board.Tile grid = 3;</code>
     */
    @Override
    public Tile getGrid(int index) {
      return grid_.get(index);
    }
    /**
     * <pre>
     * Protos only have 1D lists (row-major)
     * </pre>
     *
     * <code>repeated .board.Tile grid = 3;</code>
     */
    @Override
    public TileOrBuilder getGridOrBuilder(
        int index) {
      return grid_.get(index);
    }

    public static final int PORTALS_FIELD_NUMBER = 4;
    private java.util.List<CharacterProtos.Position> portals_;
    /**
     * <code>repeated .character.Position portals = 4;</code>
     */
    @Override
    public java.util.List<CharacterProtos.Position> getPortalsList() {
      return portals_;
    }
    /**
     * <code>repeated .character.Position portals = 4;</code>
     */
    @Override
    public java.util.List<? extends CharacterProtos.PositionOrBuilder>
        getPortalsOrBuilderList() {
      return portals_;
    }
    /**
     * <code>repeated .character.Position portals = 4;</code>
     */
    @Override
    public int getPortalsCount() {
      return portals_.size();
    }
    /**
     * <code>repeated .character.Position portals = 4;</code>
     */
    @Override
    public CharacterProtos.Position getPortals(int index) {
      return portals_.get(index);
    }
    /**
     * <code>repeated .character.Position portals = 4;</code>
     */
    @Override
    public CharacterProtos.PositionOrBuilder getPortalsOrBuilder(
        int index) {
      return portals_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rows_ != 0) {
        output.writeInt32(1, rows_);
      }
      if (columns_ != 0) {
        output.writeInt32(2, columns_);
      }
      for (int i = 0; i < grid_.size(); i++) {
        output.writeMessage(3, grid_.get(i));
      }
      for (int i = 0; i < portals_.size(); i++) {
        output.writeMessage(4, portals_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rows_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rows_);
      }
      if (columns_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, columns_);
      }
      for (int i = 0; i < grid_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, grid_.get(i));
      }
      for (int i = 0; i < portals_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, portals_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Board)) {
        return super.equals(obj);
      }
      Board other = (Board) obj;

      if (getRows()
          != other.getRows()) return false;
      if (getColumns()
          != other.getColumns()) return false;
      if (!getGridList()
          .equals(other.getGridList())) return false;
      if (!getPortalsList()
          .equals(other.getPortalsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROWS_FIELD_NUMBER;
      hash = (53 * hash) + getRows();
      hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getColumns();
      if (getGridCount() > 0) {
        hash = (37 * hash) + GRID_FIELD_NUMBER;
        hash = (53 * hash) + getGridList().hashCode();
      }
      if (getPortalsCount() > 0) {
        hash = (37 * hash) + PORTALS_FIELD_NUMBER;
        hash = (53 * hash) + getPortalsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Board parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Board parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Board parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Board parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Board parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Board parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Board parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Board parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Board parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Board parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Board parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Board parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Board prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code board.Board}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:board.Board)
        BoardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BoardProtos.internal_static_board_Board_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BoardProtos.internal_static_board_Board_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Board.class, Builder.class);
      }

      // Construct using mech.mania.engine.domain.model.BoardProtos.Board.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGridFieldBuilder();
          getPortalsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        rows_ = 0;

        columns_ = 0;

        if (gridBuilder_ == null) {
          grid_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          gridBuilder_.clear();
        }
        if (portalsBuilder_ == null) {
          portals_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          portalsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BoardProtos.internal_static_board_Board_descriptor;
      }

      @Override
      public Board getDefaultInstanceForType() {
        return Board.getDefaultInstance();
      }

      @Override
      public Board build() {
        Board result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Board buildPartial() {
        Board result = new Board(this);
        int from_bitField0_ = bitField0_;
        result.rows_ = rows_;
        result.columns_ = columns_;
        if (gridBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            grid_ = java.util.Collections.unmodifiableList(grid_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.grid_ = grid_;
        } else {
          result.grid_ = gridBuilder_.build();
        }
        if (portalsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            portals_ = java.util.Collections.unmodifiableList(portals_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.portals_ = portals_;
        } else {
          result.portals_ = portalsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Board) {
          return mergeFrom((Board)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Board other) {
        if (other == Board.getDefaultInstance()) return this;
        if (other.getRows() != 0) {
          setRows(other.getRows());
        }
        if (other.getColumns() != 0) {
          setColumns(other.getColumns());
        }
        if (gridBuilder_ == null) {
          if (!other.grid_.isEmpty()) {
            if (grid_.isEmpty()) {
              grid_ = other.grid_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGridIsMutable();
              grid_.addAll(other.grid_);
            }
            onChanged();
          }
        } else {
          if (!other.grid_.isEmpty()) {
            if (gridBuilder_.isEmpty()) {
              gridBuilder_.dispose();
              gridBuilder_ = null;
              grid_ = other.grid_;
              bitField0_ = (bitField0_ & ~0x00000001);
              gridBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGridFieldBuilder() : null;
            } else {
              gridBuilder_.addAllMessages(other.grid_);
            }
          }
        }
        if (portalsBuilder_ == null) {
          if (!other.portals_.isEmpty()) {
            if (portals_.isEmpty()) {
              portals_ = other.portals_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePortalsIsMutable();
              portals_.addAll(other.portals_);
            }
            onChanged();
          }
        } else {
          if (!other.portals_.isEmpty()) {
            if (portalsBuilder_.isEmpty()) {
              portalsBuilder_.dispose();
              portalsBuilder_ = null;
              portals_ = other.portals_;
              bitField0_ = (bitField0_ & ~0x00000002);
              portalsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPortalsFieldBuilder() : null;
            } else {
              portalsBuilder_.addAllMessages(other.portals_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Board parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Board) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rows_ ;
      /**
       * <code>int32 rows = 1;</code>
       * @return The rows.
       */
      @Override
      public int getRows() {
        return rows_;
      }
      /**
       * <code>int32 rows = 1;</code>
       * @param value The rows to set.
       * @return This builder for chaining.
       */
      public Builder setRows(int value) {

        rows_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rows = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRows() {

        rows_ = 0;
        onChanged();
        return this;
      }

      private int columns_ ;
      /**
       * <code>int32 columns = 2;</code>
       * @return The columns.
       */
      @Override
      public int getColumns() {
        return columns_;
      }
      /**
       * <code>int32 columns = 2;</code>
       * @param value The columns to set.
       * @return This builder for chaining.
       */
      public Builder setColumns(int value) {

        columns_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 columns = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearColumns() {

        columns_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Tile> grid_ =
        java.util.Collections.emptyList();
      private void ensureGridIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          grid_ = new java.util.ArrayList<Tile>(grid_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Tile, Tile.Builder, TileOrBuilder> gridBuilder_;

      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public java.util.List<Tile> getGridList() {
        if (gridBuilder_ == null) {
          return java.util.Collections.unmodifiableList(grid_);
        } else {
          return gridBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public int getGridCount() {
        if (gridBuilder_ == null) {
          return grid_.size();
        } else {
          return gridBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Tile getGrid(int index) {
        if (gridBuilder_ == null) {
          return grid_.get(index);
        } else {
          return gridBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Builder setGrid(
          int index, Tile value) {
        if (gridBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGridIsMutable();
          grid_.set(index, value);
          onChanged();
        } else {
          gridBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Builder setGrid(
          int index, Tile.Builder builderForValue) {
        if (gridBuilder_ == null) {
          ensureGridIsMutable();
          grid_.set(index, builderForValue.build());
          onChanged();
        } else {
          gridBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Builder addGrid(Tile value) {
        if (gridBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGridIsMutable();
          grid_.add(value);
          onChanged();
        } else {
          gridBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Builder addGrid(
          int index, Tile value) {
        if (gridBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGridIsMutable();
          grid_.add(index, value);
          onChanged();
        } else {
          gridBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Builder addGrid(
          Tile.Builder builderForValue) {
        if (gridBuilder_ == null) {
          ensureGridIsMutable();
          grid_.add(builderForValue.build());
          onChanged();
        } else {
          gridBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Builder addGrid(
          int index, Tile.Builder builderForValue) {
        if (gridBuilder_ == null) {
          ensureGridIsMutable();
          grid_.add(index, builderForValue.build());
          onChanged();
        } else {
          gridBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Builder addAllGrid(
          Iterable<? extends Tile> values) {
        if (gridBuilder_ == null) {
          ensureGridIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, grid_);
          onChanged();
        } else {
          gridBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Builder clearGrid() {
        if (gridBuilder_ == null) {
          grid_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          gridBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Builder removeGrid(int index) {
        if (gridBuilder_ == null) {
          ensureGridIsMutable();
          grid_.remove(index);
          onChanged();
        } else {
          gridBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Tile.Builder getGridBuilder(
          int index) {
        return getGridFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public TileOrBuilder getGridOrBuilder(
          int index) {
        if (gridBuilder_ == null) {
          return grid_.get(index);  } else {
          return gridBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public java.util.List<? extends TileOrBuilder>
           getGridOrBuilderList() {
        if (gridBuilder_ != null) {
          return gridBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(grid_);
        }
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Tile.Builder addGridBuilder() {
        return getGridFieldBuilder().addBuilder(
            Tile.getDefaultInstance());
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public Tile.Builder addGridBuilder(
          int index) {
        return getGridFieldBuilder().addBuilder(
            index, Tile.getDefaultInstance());
      }
      /**
       * <pre>
       * Protos only have 1D lists (row-major)
       * </pre>
       *
       * <code>repeated .board.Tile grid = 3;</code>
       */
      public java.util.List<Tile.Builder>
           getGridBuilderList() {
        return getGridFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Tile, Tile.Builder, TileOrBuilder>
          getGridFieldBuilder() {
        if (gridBuilder_ == null) {
          gridBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Tile, Tile.Builder, TileOrBuilder>(
                  grid_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          grid_ = null;
        }
        return gridBuilder_;
      }

      private java.util.List<CharacterProtos.Position> portals_ =
        java.util.Collections.emptyList();
      private void ensurePortalsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          portals_ = new java.util.ArrayList<CharacterProtos.Position>(portals_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          CharacterProtos.Position, CharacterProtos.Position.Builder, CharacterProtos.PositionOrBuilder> portalsBuilder_;

      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public java.util.List<CharacterProtos.Position> getPortalsList() {
        if (portalsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(portals_);
        } else {
          return portalsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public int getPortalsCount() {
        if (portalsBuilder_ == null) {
          return portals_.size();
        } else {
          return portalsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public CharacterProtos.Position getPortals(int index) {
        if (portalsBuilder_ == null) {
          return portals_.get(index);
        } else {
          return portalsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public Builder setPortals(
          int index, CharacterProtos.Position value) {
        if (portalsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePortalsIsMutable();
          portals_.set(index, value);
          onChanged();
        } else {
          portalsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public Builder setPortals(
          int index, CharacterProtos.Position.Builder builderForValue) {
        if (portalsBuilder_ == null) {
          ensurePortalsIsMutable();
          portals_.set(index, builderForValue.build());
          onChanged();
        } else {
          portalsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public Builder addPortals(CharacterProtos.Position value) {
        if (portalsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePortalsIsMutable();
          portals_.add(value);
          onChanged();
        } else {
          portalsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public Builder addPortals(
          int index, CharacterProtos.Position value) {
        if (portalsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePortalsIsMutable();
          portals_.add(index, value);
          onChanged();
        } else {
          portalsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public Builder addPortals(
          CharacterProtos.Position.Builder builderForValue) {
        if (portalsBuilder_ == null) {
          ensurePortalsIsMutable();
          portals_.add(builderForValue.build());
          onChanged();
        } else {
          portalsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public Builder addPortals(
          int index, CharacterProtos.Position.Builder builderForValue) {
        if (portalsBuilder_ == null) {
          ensurePortalsIsMutable();
          portals_.add(index, builderForValue.build());
          onChanged();
        } else {
          portalsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public Builder addAllPortals(
          Iterable<? extends CharacterProtos.Position> values) {
        if (portalsBuilder_ == null) {
          ensurePortalsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, portals_);
          onChanged();
        } else {
          portalsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public Builder clearPortals() {
        if (portalsBuilder_ == null) {
          portals_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          portalsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public Builder removePortals(int index) {
        if (portalsBuilder_ == null) {
          ensurePortalsIsMutable();
          portals_.remove(index);
          onChanged();
        } else {
          portalsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public CharacterProtos.Position.Builder getPortalsBuilder(
          int index) {
        return getPortalsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public CharacterProtos.PositionOrBuilder getPortalsOrBuilder(
          int index) {
        if (portalsBuilder_ == null) {
          return portals_.get(index);  } else {
          return portalsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public java.util.List<? extends CharacterProtos.PositionOrBuilder>
           getPortalsOrBuilderList() {
        if (portalsBuilder_ != null) {
          return portalsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(portals_);
        }
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public CharacterProtos.Position.Builder addPortalsBuilder() {
        return getPortalsFieldBuilder().addBuilder(
            CharacterProtos.Position.getDefaultInstance());
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public CharacterProtos.Position.Builder addPortalsBuilder(
          int index) {
        return getPortalsFieldBuilder().addBuilder(
            index, CharacterProtos.Position.getDefaultInstance());
      }
      /**
       * <code>repeated .character.Position portals = 4;</code>
       */
      public java.util.List<CharacterProtos.Position.Builder>
           getPortalsBuilderList() {
        return getPortalsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          CharacterProtos.Position, CharacterProtos.Position.Builder, CharacterProtos.PositionOrBuilder>
          getPortalsFieldBuilder() {
        if (portalsBuilder_ == null) {
          portalsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              CharacterProtos.Position, CharacterProtos.Position.Builder, CharacterProtos.PositionOrBuilder>(
                  portals_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          portals_ = null;
        }
        return portalsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:board.Board)
    }

    // @@protoc_insertion_point(class_scope:board.Board)
    private static final Board DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Board();
    }

    public static Board getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Board>
        PARSER = new com.google.protobuf.AbstractParser<Board>() {
      @Override
      public Board parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Board(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Board> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Board> getParserForType() {
      return PARSER;
    }

    @Override
    public Board getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:board.Tile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.board.Tile.TileType tile_type = 1;</code>
     * @return The enum numeric value on the wire for tileType.
     */
    int getTileTypeValue();
    /**
     * <code>.board.Tile.TileType tile_type = 1;</code>
     * @return The tileType.
     */
    Tile.TileType getTileType();

    /**
     * <code>repeated .item.Item items = 2;</code>
     */
    java.util.List<ItemProtos.Item>
        getItemsList();
    /**
     * <code>repeated .item.Item items = 2;</code>
     */
    ItemProtos.Item getItems(int index);
    /**
     * <code>repeated .item.Item items = 2;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .item.Item items = 2;</code>
     */
    java.util.List<? extends ItemProtos.ItemOrBuilder>
        getItemsOrBuilderList();
    /**
     * <code>repeated .item.Item items = 2;</code>
     */
    ItemProtos.ItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code board.Tile}
   */
  public static final class Tile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:board.Tile)
      TileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tile.newBuilder() to construct.
    private Tile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tile() {
      tileType_ = 0;
      items_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Tile();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              tileType_ = rawValue;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                items_ = new java.util.ArrayList<ItemProtos.Item>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(ItemProtos.Item.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BoardProtos.internal_static_board_Tile_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BoardProtos.internal_static_board_Tile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Tile.class, Builder.class);
    }

    /**
     * Protobuf enum {@code board.Tile.TileType}
     */
    public enum TileType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>VOID = 0;</code>
       */
      VOID(0),
      /**
       * <code>BLANK = 1;</code>
       */
      BLANK(1),
      /**
       * <code>IMPASSIBLE = 2;</code>
       */
      IMPASSIBLE(2),
      /**
       * <code>PORTAL = 3;</code>
       */
      PORTAL(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>VOID = 0;</code>
       */
      public static final int VOID_VALUE = 0;
      /**
       * <code>BLANK = 1;</code>
       */
      public static final int BLANK_VALUE = 1;
      /**
       * <code>IMPASSIBLE = 2;</code>
       */
      public static final int IMPASSIBLE_VALUE = 2;
      /**
       * <code>PORTAL = 3;</code>
       */
      public static final int PORTAL_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static TileType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static TileType forNumber(int value) {
        switch (value) {
          case 0: return VOID;
          case 1: return BLANK;
          case 2: return IMPASSIBLE;
          case 3: return PORTAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TileType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TileType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TileType>() {
              public TileType findValueByNumber(int number) {
                return TileType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Tile.getDescriptor().getEnumTypes().get(0);
      }

      private static final TileType[] VALUES = values();

      public static TileType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TileType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:board.Tile.TileType)
    }

    public static final int TILE_TYPE_FIELD_NUMBER = 1;
    private int tileType_;
    /**
     * <code>.board.Tile.TileType tile_type = 1;</code>
     * @return The enum numeric value on the wire for tileType.
     */
    @Override public int getTileTypeValue() {
      return tileType_;
    }
    /**
     * <code>.board.Tile.TileType tile_type = 1;</code>
     * @return The tileType.
     */
    @Override public TileType getTileType() {
      @SuppressWarnings("deprecation")
      TileType result = TileType.valueOf(tileType_);
      return result == null ? TileType.UNRECOGNIZED : result;
    }

    public static final int ITEMS_FIELD_NUMBER = 2;
    private java.util.List<ItemProtos.Item> items_;
    /**
     * <code>repeated .item.Item items = 2;</code>
     */
    @Override
    public java.util.List<ItemProtos.Item> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .item.Item items = 2;</code>
     */
    @Override
    public java.util.List<? extends ItemProtos.ItemOrBuilder>
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .item.Item items = 2;</code>
     */
    @Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .item.Item items = 2;</code>
     */
    @Override
    public ItemProtos.Item getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .item.Item items = 2;</code>
     */
    @Override
    public ItemProtos.ItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tileType_ != TileType.VOID.getNumber()) {
        output.writeEnum(1, tileType_);
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(2, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tileType_ != TileType.VOID.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, tileType_);
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Tile)) {
        return super.equals(obj);
      }
      Tile other = (Tile) obj;

      if (tileType_ != other.tileType_) return false;
      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TILE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + tileType_;
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Tile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Tile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Tile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Tile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Tile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Tile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Tile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code board.Tile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:board.Tile)
        TileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BoardProtos.internal_static_board_Tile_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BoardProtos.internal_static_board_Tile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Tile.class, Builder.class);
      }

      // Construct using mech.mania.engine.domain.model.BoardProtos.Tile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        tileType_ = 0;

        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BoardProtos.internal_static_board_Tile_descriptor;
      }

      @Override
      public Tile getDefaultInstanceForType() {
        return Tile.getDefaultInstance();
      }

      @Override
      public Tile build() {
        Tile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Tile buildPartial() {
        Tile result = new Tile(this);
        int from_bitField0_ = bitField0_;
        result.tileType_ = tileType_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Tile) {
          return mergeFrom((Tile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Tile other) {
        if (other == Tile.getDefaultInstance()) return this;
        if (other.tileType_ != 0) {
          setTileTypeValue(other.getTileTypeValue());
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Tile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Tile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int tileType_ = 0;
      /**
       * <code>.board.Tile.TileType tile_type = 1;</code>
       * @return The enum numeric value on the wire for tileType.
       */
      @Override public int getTileTypeValue() {
        return tileType_;
      }
      /**
       * <code>.board.Tile.TileType tile_type = 1;</code>
       * @param value The enum numeric value on the wire for tileType to set.
       * @return This builder for chaining.
       */
      public Builder setTileTypeValue(int value) {

        tileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.board.Tile.TileType tile_type = 1;</code>
       * @return The tileType.
       */
      @Override
      public TileType getTileType() {
        @SuppressWarnings("deprecation")
        TileType result = TileType.valueOf(tileType_);
        return result == null ? TileType.UNRECOGNIZED : result;
      }
      /**
       * <code>.board.Tile.TileType tile_type = 1;</code>
       * @param value The tileType to set.
       * @return This builder for chaining.
       */
      public Builder setTileType(TileType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        tileType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.board.Tile.TileType tile_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTileType() {

        tileType_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<ItemProtos.Item> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<ItemProtos.Item>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ItemProtos.Item, ItemProtos.Item.Builder, ItemProtos.ItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public java.util.List<ItemProtos.Item> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public ItemProtos.Item getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public Builder setItems(
          int index, ItemProtos.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public Builder setItems(
          int index, ItemProtos.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public Builder addItems(ItemProtos.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public Builder addItems(
          int index, ItemProtos.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public Builder addItems(
          ItemProtos.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public Builder addItems(
          int index, ItemProtos.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public Builder addAllItems(
          Iterable<? extends ItemProtos.Item> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public ItemProtos.Item.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public ItemProtos.ItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public java.util.List<? extends ItemProtos.ItemOrBuilder>
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public ItemProtos.Item.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            ItemProtos.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public ItemProtos.Item.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, ItemProtos.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .item.Item items = 2;</code>
       */
      public java.util.List<ItemProtos.Item.Builder>
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ItemProtos.Item, ItemProtos.Item.Builder, ItemProtos.ItemOrBuilder>
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ItemProtos.Item, ItemProtos.Item.Builder, ItemProtos.ItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:board.Tile)
    }

    // @@protoc_insertion_point(class_scope:board.Tile)
    private static final Tile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Tile();
    }

    public static Tile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tile>
        PARSER = new com.google.protobuf.AbstractParser<Tile>() {
      @Override
      public Tile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tile> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Tile> getParserForType() {
      return PARSER;
    }

    @Override
    public Tile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_board_Board_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_board_Board_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_board_Tile_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_board_Tile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013board.proto\022\005board\032\nitem.proto\032\017charac" +
      "ter.proto\"g\n\005Board\022\014\n\004rows\030\001 \001(\005\022\017\n\007colu" +
      "mns\030\002 \001(\005\022\031\n\004grid\030\003 \003(\0132\013.board.Tile\022$\n\007" +
      "portals\030\004 \003(\0132\023.character.Position\"\207\001\n\004T" +
      "ile\022\'\n\ttile_type\030\001 \001(\0162\024.board.Tile.Tile" +
      "Type\022\031\n\005items\030\002 \003(\0132\n.item.Item\";\n\010TileT" +
      "ype\022\010\n\004VOID\020\000\022\t\n\005BLANK\020\001\022\016\n\nIMPASSIBLE\020\002" +
      "\022\n\n\006PORTAL\020\003B>\n\036mech.mania.engine.domain" +
      ".modelB\013BoardProtos\252\002\016MM26.IO.Modelsb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ItemProtos.getDescriptor(),
          CharacterProtos.getDescriptor(),
        });
    internal_static_board_Board_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_board_Board_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_board_Board_descriptor,
        new String[] { "Rows", "Columns", "Grid", "Portals", });
    internal_static_board_Tile_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_board_Tile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_board_Tile_descriptor,
        new String[] { "TileType", "Items", });
    ItemProtos.getDescriptor();
    CharacterProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
