// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_state.proto

package mech.mania.engine.domain.model;

public final class GameStateProtos {
  private GameStateProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:game_state.GameState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 state_id = 1;</code>
     * @return The stateId.
     */
    long getStateId();

    /**
     * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
     */
    int getBoardNamesCount();
    /**
     * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
     */
    boolean containsBoardNames(
        String key);
    /**
     * Use {@link #getBoardNamesMap()} instead.
     */
    @Deprecated
    java.util.Map<String, BoardProtos.Board>
    getBoardNames();
    /**
     * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
     */
    java.util.Map<String, BoardProtos.Board>
    getBoardNamesMap();
    /**
     * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
     */

    BoardProtos.Board getBoardNamesOrDefault(
        String key,
        BoardProtos.Board defaultValue);
    /**
     * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
     */

    BoardProtos.Board getBoardNamesOrThrow(
        String key);

    /**
     * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
     */
    int getPlayerNamesCount();
    /**
     * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
     */
    boolean containsPlayerNames(
        String key);
    /**
     * Use {@link #getPlayerNamesMap()} instead.
     */
    @Deprecated
    java.util.Map<String, CharacterProtos.Player>
    getPlayerNames();
    /**
     * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
     */
    java.util.Map<String, CharacterProtos.Player>
    getPlayerNamesMap();
    /**
     * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
     */

    CharacterProtos.Player getPlayerNamesOrDefault(
        String key,
        CharacterProtos.Player defaultValue);
    /**
     * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
     */

    CharacterProtos.Player getPlayerNamesOrThrow(
        String key);

    /**
     * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
     */
    int getMonsterNamesCount();
    /**
     * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
     */
    boolean containsMonsterNames(
        String key);
    /**
     * Use {@link #getMonsterNamesMap()} instead.
     */
    @Deprecated
    java.util.Map<String, CharacterProtos.Monster>
    getMonsterNames();
    /**
     * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
     */
    java.util.Map<String, CharacterProtos.Monster>
    getMonsterNamesMap();
    /**
     * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
     */

    CharacterProtos.Monster getMonsterNamesOrDefault(
        String key,
        CharacterProtos.Monster defaultValue);
    /**
     * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
     */

    CharacterProtos.Monster getMonsterNamesOrThrow(
        String key);
  }
  /**
   * Protobuf type {@code game_state.GameState}
   */
  public static final class GameState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:game_state.GameState)
      GameStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameState.newBuilder() to construct.
    private GameState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameState() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameState();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              stateId_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                boardNames_ = com.google.protobuf.MapField.newMapField(
                    BoardNamesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<String, BoardProtos.Board>
              boardNames__ = input.readMessage(
                  BoardNamesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              boardNames_.getMutableMap().put(
                  boardNames__.getKey(), boardNames__.getValue());
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                playerNames_ = com.google.protobuf.MapField.newMapField(
                    PlayerNamesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<String, CharacterProtos.Player>
              playerNames__ = input.readMessage(
                  PlayerNamesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              playerNames_.getMutableMap().put(
                  playerNames__.getKey(), playerNames__.getValue());
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                monsterNames_ = com.google.protobuf.MapField.newMapField(
                    MonsterNamesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<String, CharacterProtos.Monster>
              monsterNames__ = input.readMessage(
                  MonsterNamesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              monsterNames_.getMutableMap().put(
                  monsterNames__.getKey(), monsterNames__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GameStateProtos.internal_static_game_state_GameState_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetBoardNames();
        case 3:
          return internalGetPlayerNames();
        case 4:
          return internalGetMonsterNames();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GameStateProtos.internal_static_game_state_GameState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GameState.class, Builder.class);
    }

    public static final int STATE_ID_FIELD_NUMBER = 1;
    private long stateId_;
    /**
     * <code>int64 state_id = 1;</code>
     * @return The stateId.
     */
    @Override
    public long getStateId() {
      return stateId_;
    }

    public static final int BOARD_NAMES_FIELD_NUMBER = 2;
    private static final class BoardNamesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, BoardProtos.Board> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, BoardProtos.Board>newDefaultInstance(
                  GameStateProtos.internal_static_game_state_GameState_BoardNamesEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  BoardProtos.Board.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, BoardProtos.Board> boardNames_;
    private com.google.protobuf.MapField<String, BoardProtos.Board>
    internalGetBoardNames() {
      if (boardNames_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            BoardNamesDefaultEntryHolder.defaultEntry);
      }
      return boardNames_;
    }

    public int getBoardNamesCount() {
      return internalGetBoardNames().getMap().size();
    }
    /**
     * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
     */

    @Override
    public boolean containsBoardNames(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetBoardNames().getMap().containsKey(key);
    }
    /**
     * Use {@link #getBoardNamesMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, BoardProtos.Board> getBoardNames() {
      return getBoardNamesMap();
    }
    /**
     * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
     */
    @Override

    public java.util.Map<String, BoardProtos.Board> getBoardNamesMap() {
      return internalGetBoardNames().getMap();
    }
    /**
     * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
     */
    @Override

    public BoardProtos.Board getBoardNamesOrDefault(
        String key,
        BoardProtos.Board defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, BoardProtos.Board> map =
          internalGetBoardNames().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
     */
    @Override

    public BoardProtos.Board getBoardNamesOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, BoardProtos.Board> map =
          internalGetBoardNames().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int PLAYER_NAMES_FIELD_NUMBER = 3;
    private static final class PlayerNamesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, CharacterProtos.Player> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, CharacterProtos.Player>newDefaultInstance(
                  GameStateProtos.internal_static_game_state_GameState_PlayerNamesEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  CharacterProtos.Player.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, CharacterProtos.Player> playerNames_;
    private com.google.protobuf.MapField<String, CharacterProtos.Player>
    internalGetPlayerNames() {
      if (playerNames_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PlayerNamesDefaultEntryHolder.defaultEntry);
      }
      return playerNames_;
    }

    public int getPlayerNamesCount() {
      return internalGetPlayerNames().getMap().size();
    }
    /**
     * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
     */

    @Override
    public boolean containsPlayerNames(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetPlayerNames().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPlayerNamesMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, CharacterProtos.Player> getPlayerNames() {
      return getPlayerNamesMap();
    }
    /**
     * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
     */
    @Override

    public java.util.Map<String, CharacterProtos.Player> getPlayerNamesMap() {
      return internalGetPlayerNames().getMap();
    }
    /**
     * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
     */
    @Override

    public CharacterProtos.Player getPlayerNamesOrDefault(
        String key,
        CharacterProtos.Player defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, CharacterProtos.Player> map =
          internalGetPlayerNames().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
     */
    @Override

    public CharacterProtos.Player getPlayerNamesOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, CharacterProtos.Player> map =
          internalGetPlayerNames().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int MONSTER_NAMES_FIELD_NUMBER = 4;
    private static final class MonsterNamesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, CharacterProtos.Monster> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, CharacterProtos.Monster>newDefaultInstance(
                  GameStateProtos.internal_static_game_state_GameState_MonsterNamesEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  CharacterProtos.Monster.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, CharacterProtos.Monster> monsterNames_;
    private com.google.protobuf.MapField<String, CharacterProtos.Monster>
    internalGetMonsterNames() {
      if (monsterNames_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MonsterNamesDefaultEntryHolder.defaultEntry);
      }
      return monsterNames_;
    }

    public int getMonsterNamesCount() {
      return internalGetMonsterNames().getMap().size();
    }
    /**
     * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
     */

    @Override
    public boolean containsMonsterNames(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetMonsterNames().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMonsterNamesMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, CharacterProtos.Monster> getMonsterNames() {
      return getMonsterNamesMap();
    }
    /**
     * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
     */
    @Override

    public java.util.Map<String, CharacterProtos.Monster> getMonsterNamesMap() {
      return internalGetMonsterNames().getMap();
    }
    /**
     * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
     */
    @Override

    public CharacterProtos.Monster getMonsterNamesOrDefault(
        String key,
        CharacterProtos.Monster defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, CharacterProtos.Monster> map =
          internalGetMonsterNames().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
     */
    @Override

    public CharacterProtos.Monster getMonsterNamesOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, CharacterProtos.Monster> map =
          internalGetMonsterNames().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stateId_ != 0L) {
        output.writeInt64(1, stateId_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetBoardNames(),
          BoardNamesDefaultEntryHolder.defaultEntry,
          2);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetPlayerNames(),
          PlayerNamesDefaultEntryHolder.defaultEntry,
          3);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMonsterNames(),
          MonsterNamesDefaultEntryHolder.defaultEntry,
          4);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stateId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, stateId_);
      }
      for (java.util.Map.Entry<String, BoardProtos.Board> entry
           : internalGetBoardNames().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, BoardProtos.Board>
        boardNames__ = BoardNamesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, boardNames__);
      }
      for (java.util.Map.Entry<String, CharacterProtos.Player> entry
           : internalGetPlayerNames().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, CharacterProtos.Player>
        playerNames__ = PlayerNamesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, playerNames__);
      }
      for (java.util.Map.Entry<String, CharacterProtos.Monster> entry
           : internalGetMonsterNames().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, CharacterProtos.Monster>
        monsterNames__ = MonsterNamesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, monsterNames__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GameState)) {
        return super.equals(obj);
      }
      GameState other = (GameState) obj;

      if (getStateId()
          != other.getStateId()) return false;
      if (!internalGetBoardNames().equals(
          other.internalGetBoardNames())) return false;
      if (!internalGetPlayerNames().equals(
          other.internalGetPlayerNames())) return false;
      if (!internalGetMonsterNames().equals(
          other.internalGetMonsterNames())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStateId());
      if (!internalGetBoardNames().getMap().isEmpty()) {
        hash = (37 * hash) + BOARD_NAMES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetBoardNames().hashCode();
      }
      if (!internalGetPlayerNames().getMap().isEmpty()) {
        hash = (37 * hash) + PLAYER_NAMES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetPlayerNames().hashCode();
      }
      if (!internalGetMonsterNames().getMap().isEmpty()) {
        hash = (37 * hash) + MONSTER_NAMES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMonsterNames().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GameState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GameState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GameState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GameState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GameState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GameState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GameState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game_state.GameState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:game_state.GameState)
        GameStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GameStateProtos.internal_static_game_state_GameState_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetBoardNames();
          case 3:
            return internalGetPlayerNames();
          case 4:
            return internalGetMonsterNames();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableBoardNames();
          case 3:
            return internalGetMutablePlayerNames();
          case 4:
            return internalGetMutableMonsterNames();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GameStateProtos.internal_static_game_state_GameState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GameState.class, Builder.class);
      }

      // Construct using mech.mania.engine.domain.model.GameStateProtos.GameState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        stateId_ = 0L;

        internalGetMutableBoardNames().clear();
        internalGetMutablePlayerNames().clear();
        internalGetMutableMonsterNames().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GameStateProtos.internal_static_game_state_GameState_descriptor;
      }

      @Override
      public GameState getDefaultInstanceForType() {
        return GameState.getDefaultInstance();
      }

      @Override
      public GameState build() {
        GameState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GameState buildPartial() {
        GameState result = new GameState(this);
        int from_bitField0_ = bitField0_;
        result.stateId_ = stateId_;
        result.boardNames_ = internalGetBoardNames();
        result.boardNames_.makeImmutable();
        result.playerNames_ = internalGetPlayerNames();
        result.playerNames_.makeImmutable();
        result.monsterNames_ = internalGetMonsterNames();
        result.monsterNames_.makeImmutable();
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GameState) {
          return mergeFrom((GameState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GameState other) {
        if (other == GameState.getDefaultInstance()) return this;
        if (other.getStateId() != 0L) {
          setStateId(other.getStateId());
        }
        internalGetMutableBoardNames().mergeFrom(
            other.internalGetBoardNames());
        internalGetMutablePlayerNames().mergeFrom(
            other.internalGetPlayerNames());
        internalGetMutableMonsterNames().mergeFrom(
            other.internalGetMonsterNames());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GameState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GameState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long stateId_ ;
      /**
       * <code>int64 state_id = 1;</code>
       * @return The stateId.
       */
      @Override
      public long getStateId() {
        return stateId_;
      }
      /**
       * <code>int64 state_id = 1;</code>
       * @param value The stateId to set.
       * @return This builder for chaining.
       */
      public Builder setStateId(long value) {

        stateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 state_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStateId() {

        stateId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, BoardProtos.Board> boardNames_;
      private com.google.protobuf.MapField<String, BoardProtos.Board>
      internalGetBoardNames() {
        if (boardNames_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              BoardNamesDefaultEntryHolder.defaultEntry);
        }
        return boardNames_;
      }
      private com.google.protobuf.MapField<String, BoardProtos.Board>
      internalGetMutableBoardNames() {
        onChanged();;
        if (boardNames_ == null) {
          boardNames_ = com.google.protobuf.MapField.newMapField(
              BoardNamesDefaultEntryHolder.defaultEntry);
        }
        if (!boardNames_.isMutable()) {
          boardNames_ = boardNames_.copy();
        }
        return boardNames_;
      }

      public int getBoardNamesCount() {
        return internalGetBoardNames().getMap().size();
      }
      /**
       * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
       */

      @Override
      public boolean containsBoardNames(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetBoardNames().getMap().containsKey(key);
      }
      /**
       * Use {@link #getBoardNamesMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<String, BoardProtos.Board> getBoardNames() {
        return getBoardNamesMap();
      }
      /**
       * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
       */
      @Override

      public java.util.Map<String, BoardProtos.Board> getBoardNamesMap() {
        return internalGetBoardNames().getMap();
      }
      /**
       * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
       */
      @Override

      public BoardProtos.Board getBoardNamesOrDefault(
          String key,
          BoardProtos.Board defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, BoardProtos.Board> map =
            internalGetBoardNames().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
       */
      @Override

      public BoardProtos.Board getBoardNamesOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, BoardProtos.Board> map =
            internalGetBoardNames().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearBoardNames() {
        internalGetMutableBoardNames().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
       */

      public Builder removeBoardNames(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableBoardNames().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, BoardProtos.Board>
      getMutableBoardNames() {
        return internalGetMutableBoardNames().getMutableMap();
      }
      /**
       * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
       */
      public Builder putBoardNames(
          String key,
          BoardProtos.Board value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableBoardNames().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .board.Board&gt; board_names = 2;</code>
       */

      public Builder putAllBoardNames(
          java.util.Map<String, BoardProtos.Board> values) {
        internalGetMutableBoardNames().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          String, CharacterProtos.Player> playerNames_;
      private com.google.protobuf.MapField<String, CharacterProtos.Player>
      internalGetPlayerNames() {
        if (playerNames_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PlayerNamesDefaultEntryHolder.defaultEntry);
        }
        return playerNames_;
      }
      private com.google.protobuf.MapField<String, CharacterProtos.Player>
      internalGetMutablePlayerNames() {
        onChanged();;
        if (playerNames_ == null) {
          playerNames_ = com.google.protobuf.MapField.newMapField(
              PlayerNamesDefaultEntryHolder.defaultEntry);
        }
        if (!playerNames_.isMutable()) {
          playerNames_ = playerNames_.copy();
        }
        return playerNames_;
      }

      public int getPlayerNamesCount() {
        return internalGetPlayerNames().getMap().size();
      }
      /**
       * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
       */

      @Override
      public boolean containsPlayerNames(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetPlayerNames().getMap().containsKey(key);
      }
      /**
       * Use {@link #getPlayerNamesMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<String, CharacterProtos.Player> getPlayerNames() {
        return getPlayerNamesMap();
      }
      /**
       * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
       */
      @Override

      public java.util.Map<String, CharacterProtos.Player> getPlayerNamesMap() {
        return internalGetPlayerNames().getMap();
      }
      /**
       * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
       */
      @Override

      public CharacterProtos.Player getPlayerNamesOrDefault(
          String key,
          CharacterProtos.Player defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, CharacterProtos.Player> map =
            internalGetPlayerNames().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
       */
      @Override

      public CharacterProtos.Player getPlayerNamesOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, CharacterProtos.Player> map =
            internalGetPlayerNames().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearPlayerNames() {
        internalGetMutablePlayerNames().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
       */

      public Builder removePlayerNames(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutablePlayerNames().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, CharacterProtos.Player>
      getMutablePlayerNames() {
        return internalGetMutablePlayerNames().getMutableMap();
      }
      /**
       * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
       */
      public Builder putPlayerNames(
          String key,
          CharacterProtos.Player value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutablePlayerNames().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .character.Player&gt; player_names = 3;</code>
       */

      public Builder putAllPlayerNames(
          java.util.Map<String, CharacterProtos.Player> values) {
        internalGetMutablePlayerNames().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          String, CharacterProtos.Monster> monsterNames_;
      private com.google.protobuf.MapField<String, CharacterProtos.Monster>
      internalGetMonsterNames() {
        if (monsterNames_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MonsterNamesDefaultEntryHolder.defaultEntry);
        }
        return monsterNames_;
      }
      private com.google.protobuf.MapField<String, CharacterProtos.Monster>
      internalGetMutableMonsterNames() {
        onChanged();;
        if (monsterNames_ == null) {
          monsterNames_ = com.google.protobuf.MapField.newMapField(
              MonsterNamesDefaultEntryHolder.defaultEntry);
        }
        if (!monsterNames_.isMutable()) {
          monsterNames_ = monsterNames_.copy();
        }
        return monsterNames_;
      }

      public int getMonsterNamesCount() {
        return internalGetMonsterNames().getMap().size();
      }
      /**
       * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
       */

      @Override
      public boolean containsMonsterNames(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetMonsterNames().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMonsterNamesMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<String, CharacterProtos.Monster> getMonsterNames() {
        return getMonsterNamesMap();
      }
      /**
       * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
       */
      @Override

      public java.util.Map<String, CharacterProtos.Monster> getMonsterNamesMap() {
        return internalGetMonsterNames().getMap();
      }
      /**
       * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
       */
      @Override

      public CharacterProtos.Monster getMonsterNamesOrDefault(
          String key,
          CharacterProtos.Monster defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, CharacterProtos.Monster> map =
            internalGetMonsterNames().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
       */
      @Override

      public CharacterProtos.Monster getMonsterNamesOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, CharacterProtos.Monster> map =
            internalGetMonsterNames().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMonsterNames() {
        internalGetMutableMonsterNames().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
       */

      public Builder removeMonsterNames(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableMonsterNames().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, CharacterProtos.Monster>
      getMutableMonsterNames() {
        return internalGetMutableMonsterNames().getMutableMap();
      }
      /**
       * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
       */
      public Builder putMonsterNames(
          String key,
          CharacterProtos.Monster value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableMonsterNames().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .character.Monster&gt; monster_names = 4;</code>
       */

      public Builder putAllMonsterNames(
          java.util.Map<String, CharacterProtos.Monster> values) {
        internalGetMutableMonsterNames().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:game_state.GameState)
    }

    // @@protoc_insertion_point(class_scope:game_state.GameState)
    private static final GameState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GameState();
    }

    public static GameState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameState>
        PARSER = new com.google.protobuf.AbstractParser<GameState>() {
      @Override
      public GameState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameState> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GameState> getParserForType() {
      return PARSER;
    }

    @Override
    public GameState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GameChangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:game_state.GameChange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 change_id = 1;</code>
     * @return The changeId.
     */
    long getChangeId();
  }
  /**
   * Protobuf type {@code game_state.GameChange}
   */
  public static final class GameChange extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:game_state.GameChange)
      GameChangeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameChange.newBuilder() to construct.
    private GameChange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameChange() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameChange();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameChange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              changeId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GameStateProtos.internal_static_game_state_GameChange_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GameStateProtos.internal_static_game_state_GameChange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GameChange.class, Builder.class);
    }

    public static final int CHANGE_ID_FIELD_NUMBER = 1;
    private long changeId_;
    /**
     * <code>int64 change_id = 1;</code>
     * @return The changeId.
     */
    @Override
    public long getChangeId() {
      return changeId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (changeId_ != 0L) {
        output.writeInt64(1, changeId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (changeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, changeId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GameChange)) {
        return super.equals(obj);
      }
      GameChange other = (GameChange) obj;

      if (getChangeId()
          != other.getChangeId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHANGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChangeId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GameChange parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameChange parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameChange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameChange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameChange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameChange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameChange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GameChange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GameChange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GameChange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GameChange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GameChange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GameChange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code game_state.GameChange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:game_state.GameChange)
        GameChangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GameStateProtos.internal_static_game_state_GameChange_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GameStateProtos.internal_static_game_state_GameChange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GameChange.class, Builder.class);
      }

      // Construct using mech.mania.engine.domain.model.GameStateProtos.GameChange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        changeId_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GameStateProtos.internal_static_game_state_GameChange_descriptor;
      }

      @Override
      public GameChange getDefaultInstanceForType() {
        return GameChange.getDefaultInstance();
      }

      @Override
      public GameChange build() {
        GameChange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GameChange buildPartial() {
        GameChange result = new GameChange(this);
        result.changeId_ = changeId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GameChange) {
          return mergeFrom((GameChange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GameChange other) {
        if (other == GameChange.getDefaultInstance()) return this;
        if (other.getChangeId() != 0L) {
          setChangeId(other.getChangeId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GameChange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GameChange) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long changeId_ ;
      /**
       * <code>int64 change_id = 1;</code>
       * @return The changeId.
       */
      @Override
      public long getChangeId() {
        return changeId_;
      }
      /**
       * <code>int64 change_id = 1;</code>
       * @param value The changeId to set.
       * @return This builder for chaining.
       */
      public Builder setChangeId(long value) {

        changeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 change_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChangeId() {

        changeId_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:game_state.GameChange)
    }

    // @@protoc_insertion_point(class_scope:game_state.GameChange)
    private static final GameChange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GameChange();
    }

    public static GameChange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameChange>
        PARSER = new com.google.protobuf.AbstractParser<GameChange>() {
      @Override
      public GameChange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameChange(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameChange> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GameChange> getParserForType() {
      return PARSER;
    }

    @Override
    public GameChange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_state_GameState_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_state_GameState_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_state_GameState_BoardNamesEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_state_GameState_BoardNamesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_state_GameState_PlayerNamesEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_state_GameState_PlayerNamesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_state_GameState_MonsterNamesEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_state_GameState_MonsterNamesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_state_GameChange_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_state_GameChange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020game_state.proto\022\ngame_state\032\013board.pr" +
      "oto\032\017character.proto\"\250\003\n\tGameState\022\020\n\010st" +
      "ate_id\030\001 \001(\003\022:\n\013board_names\030\002 \003(\0132%.game" +
      "_state.GameState.BoardNamesEntry\022<\n\014play" +
      "er_names\030\003 \003(\0132&.game_state.GameState.Pl" +
      "ayerNamesEntry\022>\n\rmonster_names\030\004 \003(\0132\'." +
      "game_state.GameState.MonsterNamesEntry\032?" +
      "\n\017BoardNamesEntry\022\013\n\003key\030\001 \001(\t\022\033\n\005value\030" +
      "\002 \001(\0132\014.board.Board:\0028\001\032E\n\020PlayerNamesEn" +
      "try\022\013\n\003key\030\001 \001(\t\022 \n\005value\030\002 \001(\0132\021.charac" +
      "ter.Player:\0028\001\032G\n\021MonsterNamesEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022!\n\005value\030\002 \001(\0132\022.character.Mons" +
      "ter:\0028\001\"\037\n\nGameChange\022\021\n\tchange_id\030\001 \001(\003" +
      "BB\n\036mech.mania.engine.domain.modelB\017Game" +
      "StateProtos\252\002\016MM26.IO.Modelsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          BoardProtos.getDescriptor(),
          CharacterProtos.getDescriptor(),
        });
    internal_static_game_state_GameState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_game_state_GameState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_state_GameState_descriptor,
        new String[] { "StateId", "BoardNames", "PlayerNames", "MonsterNames", });
    internal_static_game_state_GameState_BoardNamesEntry_descriptor =
      internal_static_game_state_GameState_descriptor.getNestedTypes().get(0);
    internal_static_game_state_GameState_BoardNamesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_state_GameState_BoardNamesEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_game_state_GameState_PlayerNamesEntry_descriptor =
      internal_static_game_state_GameState_descriptor.getNestedTypes().get(1);
    internal_static_game_state_GameState_PlayerNamesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_state_GameState_PlayerNamesEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_game_state_GameState_MonsterNamesEntry_descriptor =
      internal_static_game_state_GameState_descriptor.getNestedTypes().get(2);
    internal_static_game_state_GameState_MonsterNamesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_state_GameState_MonsterNamesEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_game_state_GameChange_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_game_state_GameChange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_state_GameChange_descriptor,
        new String[] { "ChangeId", });
    BoardProtos.getDescriptor();
    CharacterProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
