// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

package mech.mania.engine.domain.model;

public final class PlayerProtos {
  private PlayerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerTurnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:player_communication.PlayerTurn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.game_state.GameState game_state = 1;</code>
     * @return Whether the gameState field is set.
     */
    boolean hasGameState();
    /**
     * <code>.game_state.GameState game_state = 1;</code>
     * @return The gameState.
     */
    GameStateProtos.GameState getGameState();
    /**
     * <code>.game_state.GameState game_state = 1;</code>
     */
    GameStateProtos.GameStateOrBuilder getGameStateOrBuilder();

    /**
     * <code>string player_name = 2;</code>
     * @return The playerName.
     */
    String getPlayerName();
    /**
     * <code>string player_name = 2;</code>
     * @return The bytes for playerName.
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();
  }
  /**
   * <pre>
   * Proto sent from engine to player
   * </pre>
   *
   * Protobuf type {@code player_communication.PlayerTurn}
   */
  public static final class PlayerTurn extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:player_communication.PlayerTurn)
      PlayerTurnOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerTurn.newBuilder() to construct.
    private PlayerTurn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerTurn() {
      playerName_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerTurn();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerTurn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              GameStateProtos.GameState.Builder subBuilder = null;
              if (gameState_ != null) {
                subBuilder = gameState_.toBuilder();
              }
              gameState_ = input.readMessage(GameStateProtos.GameState.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(gameState_);
                gameState_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              playerName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlayerProtos.internal_static_player_communication_PlayerTurn_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlayerProtos.internal_static_player_communication_PlayerTurn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PlayerTurn.class, Builder.class);
    }

    public static final int GAME_STATE_FIELD_NUMBER = 1;
    private GameStateProtos.GameState gameState_;
    /**
     * <code>.game_state.GameState game_state = 1;</code>
     * @return Whether the gameState field is set.
     */
    @Override
    public boolean hasGameState() {
      return gameState_ != null;
    }
    /**
     * <code>.game_state.GameState game_state = 1;</code>
     * @return The gameState.
     */
    @Override
    public GameStateProtos.GameState getGameState() {
      return gameState_ == null ? GameStateProtos.GameState.getDefaultInstance() : gameState_;
    }
    /**
     * <code>.game_state.GameState game_state = 1;</code>
     */
    @Override
    public GameStateProtos.GameStateOrBuilder getGameStateOrBuilder() {
      return getGameState();
    }

    public static final int PLAYER_NAME_FIELD_NUMBER = 2;
    private volatile Object playerName_;
    /**
     * <code>string player_name = 2;</code>
     * @return The playerName.
     */
    @Override
    public String getPlayerName() {
      Object ref = playerName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        playerName_ = s;
        return s;
      }
    }
    /**
     * <code>string player_name = 2;</code>
     * @return The bytes for playerName.
     */
    @Override
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      Object ref = playerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (gameState_ != null) {
        output.writeMessage(1, getGameState());
      }
      if (!getPlayerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, playerName_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (gameState_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGameState());
      }
      if (!getPlayerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, playerName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PlayerTurn)) {
        return super.equals(obj);
      }
      PlayerTurn other = (PlayerTurn) obj;

      if (hasGameState() != other.hasGameState()) return false;
      if (hasGameState()) {
        if (!getGameState()
            .equals(other.getGameState())) return false;
      }
      if (!getPlayerName()
          .equals(other.getPlayerName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGameState()) {
        hash = (37 * hash) + GAME_STATE_FIELD_NUMBER;
        hash = (53 * hash) + getGameState().hashCode();
      }
      hash = (37 * hash) + PLAYER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PlayerTurn parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerTurn parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerTurn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerTurn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerTurn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerTurn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerTurn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlayerTurn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlayerTurn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PlayerTurn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlayerTurn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlayerTurn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PlayerTurn prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Proto sent from engine to player
     * </pre>
     *
     * Protobuf type {@code player_communication.PlayerTurn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:player_communication.PlayerTurn)
        PlayerTurnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlayerProtos.internal_static_player_communication_PlayerTurn_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlayerProtos.internal_static_player_communication_PlayerTurn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PlayerTurn.class, Builder.class);
      }

      // Construct using mech.mania.engine.domain.model.PlayerProtos.PlayerTurn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (gameStateBuilder_ == null) {
          gameState_ = null;
        } else {
          gameState_ = null;
          gameStateBuilder_ = null;
        }
        playerName_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlayerProtos.internal_static_player_communication_PlayerTurn_descriptor;
      }

      @Override
      public PlayerTurn getDefaultInstanceForType() {
        return PlayerTurn.getDefaultInstance();
      }

      @Override
      public PlayerTurn build() {
        PlayerTurn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PlayerTurn buildPartial() {
        PlayerTurn result = new PlayerTurn(this);
        if (gameStateBuilder_ == null) {
          result.gameState_ = gameState_;
        } else {
          result.gameState_ = gameStateBuilder_.build();
        }
        result.playerName_ = playerName_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PlayerTurn) {
          return mergeFrom((PlayerTurn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PlayerTurn other) {
        if (other == PlayerTurn.getDefaultInstance()) return this;
        if (other.hasGameState()) {
          mergeGameState(other.getGameState());
        }
        if (!other.getPlayerName().isEmpty()) {
          playerName_ = other.playerName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PlayerTurn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PlayerTurn) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private GameStateProtos.GameState gameState_;
      private com.google.protobuf.SingleFieldBuilderV3<
          GameStateProtos.GameState, GameStateProtos.GameState.Builder, GameStateProtos.GameStateOrBuilder> gameStateBuilder_;
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       * @return Whether the gameState field is set.
       */
      public boolean hasGameState() {
        return gameStateBuilder_ != null || gameState_ != null;
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       * @return The gameState.
       */
      public GameStateProtos.GameState getGameState() {
        if (gameStateBuilder_ == null) {
          return gameState_ == null ? GameStateProtos.GameState.getDefaultInstance() : gameState_;
        } else {
          return gameStateBuilder_.getMessage();
        }
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      public Builder setGameState(GameStateProtos.GameState value) {
        if (gameStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gameState_ = value;
          onChanged();
        } else {
          gameStateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      public Builder setGameState(
          GameStateProtos.GameState.Builder builderForValue) {
        if (gameStateBuilder_ == null) {
          gameState_ = builderForValue.build();
          onChanged();
        } else {
          gameStateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      public Builder mergeGameState(GameStateProtos.GameState value) {
        if (gameStateBuilder_ == null) {
          if (gameState_ != null) {
            gameState_ =
              GameStateProtos.GameState.newBuilder(gameState_).mergeFrom(value).buildPartial();
          } else {
            gameState_ = value;
          }
          onChanged();
        } else {
          gameStateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      public Builder clearGameState() {
        if (gameStateBuilder_ == null) {
          gameState_ = null;
          onChanged();
        } else {
          gameState_ = null;
          gameStateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      public GameStateProtos.GameState.Builder getGameStateBuilder() {

        onChanged();
        return getGameStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      public GameStateProtos.GameStateOrBuilder getGameStateOrBuilder() {
        if (gameStateBuilder_ != null) {
          return gameStateBuilder_.getMessageOrBuilder();
        } else {
          return gameState_ == null ?
              GameStateProtos.GameState.getDefaultInstance() : gameState_;
        }
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          GameStateProtos.GameState, GameStateProtos.GameState.Builder, GameStateProtos.GameStateOrBuilder>
          getGameStateFieldBuilder() {
        if (gameStateBuilder_ == null) {
          gameStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              GameStateProtos.GameState, GameStateProtos.GameState.Builder, GameStateProtos.GameStateOrBuilder>(
                  getGameState(),
                  getParentForChildren(),
                  isClean());
          gameState_ = null;
        }
        return gameStateBuilder_;
      }

      private Object playerName_ = "";
      /**
       * <code>string player_name = 2;</code>
       * @return The playerName.
       */
      public String getPlayerName() {
        Object ref = playerName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string player_name = 2;</code>
       * @return The bytes for playerName.
       */
      public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        Object ref = playerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          playerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string player_name = 2;</code>
       * @param value The playerName to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        playerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string player_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerName() {

        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      /**
       * <code>string player_name = 2;</code>
       * @param value The bytes for playerName to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        playerName_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:player_communication.PlayerTurn)
    }

    // @@protoc_insertion_point(class_scope:player_communication.PlayerTurn)
    private static final PlayerTurn DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlayerTurn();
    }

    public static PlayerTurn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerTurn>
        PARSER = new com.google.protobuf.AbstractParser<PlayerTurn>() {
      @Override
      public PlayerTurn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerTurn(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerTurn> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PlayerTurn> getParserForType() {
      return PARSER;
    }

    @Override
    public PlayerTurn getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerDecisionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:player_communication.PlayerDecision)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.character.DecisionType decision_type = 1;</code>
     * @return The enum numeric value on the wire for decisionType.
     */
    int getDecisionTypeValue();
    /**
     * <code>.character.DecisionType decision_type = 1;</code>
     * @return The decisionType.
     */
    CharacterProtos.DecisionType getDecisionType();

    /**
     * <pre>
     * For MOVE, ATTACK
     * </pre>
     *
     * <code>.character.Position target_position = 2;</code>
     * @return Whether the targetPosition field is set.
     */
    boolean hasTargetPosition();
    /**
     * <pre>
     * For MOVE, ATTACK
     * </pre>
     *
     * <code>.character.Position target_position = 2;</code>
     * @return The targetPosition.
     */
    CharacterProtos.Position getTargetPosition();
    /**
     * <pre>
     * For MOVE, ATTACK
     * </pre>
     *
     * <code>.character.Position target_position = 2;</code>
     */
    CharacterProtos.PositionOrBuilder getTargetPositionOrBuilder();

    /**
     * <pre>
     * For TRAVEL, DROP, EQUIP, PICKUP
     * </pre>
     *
     * <code>int32 index = 3;</code>
     * @return The index.
     */
    int getIndex();
  }
  /**
   * <pre>
   * Proto sent from player to engine
   * </pre>
   *
   * Protobuf type {@code player_communication.PlayerDecision}
   */
  public static final class PlayerDecision extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:player_communication.PlayerDecision)
      PlayerDecisionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerDecision.newBuilder() to construct.
    private PlayerDecision(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerDecision() {
      decisionType_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerDecision();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerDecision(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              decisionType_ = rawValue;
              break;
            }
            case 18: {
              CharacterProtos.Position.Builder subBuilder = null;
              if (targetPosition_ != null) {
                subBuilder = targetPosition_.toBuilder();
              }
              targetPosition_ = input.readMessage(CharacterProtos.Position.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(targetPosition_);
                targetPosition_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              index_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlayerProtos.internal_static_player_communication_PlayerDecision_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlayerProtos.internal_static_player_communication_PlayerDecision_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PlayerDecision.class, Builder.class);
    }

    public static final int DECISION_TYPE_FIELD_NUMBER = 1;
    private int decisionType_;
    /**
     * <code>.character.DecisionType decision_type = 1;</code>
     * @return The enum numeric value on the wire for decisionType.
     */
    @Override public int getDecisionTypeValue() {
      return decisionType_;
    }
    /**
     * <code>.character.DecisionType decision_type = 1;</code>
     * @return The decisionType.
     */
    @Override public CharacterProtos.DecisionType getDecisionType() {
      @SuppressWarnings("deprecation")
      CharacterProtos.DecisionType result = CharacterProtos.DecisionType.valueOf(decisionType_);
      return result == null ? CharacterProtos.DecisionType.UNRECOGNIZED : result;
    }

    public static final int TARGET_POSITION_FIELD_NUMBER = 2;
    private CharacterProtos.Position targetPosition_;
    /**
     * <pre>
     * For MOVE, ATTACK
     * </pre>
     *
     * <code>.character.Position target_position = 2;</code>
     * @return Whether the targetPosition field is set.
     */
    @Override
    public boolean hasTargetPosition() {
      return targetPosition_ != null;
    }
    /**
     * <pre>
     * For MOVE, ATTACK
     * </pre>
     *
     * <code>.character.Position target_position = 2;</code>
     * @return The targetPosition.
     */
    @Override
    public CharacterProtos.Position getTargetPosition() {
      return targetPosition_ == null ? CharacterProtos.Position.getDefaultInstance() : targetPosition_;
    }
    /**
     * <pre>
     * For MOVE, ATTACK
     * </pre>
     *
     * <code>.character.Position target_position = 2;</code>
     */
    @Override
    public CharacterProtos.PositionOrBuilder getTargetPositionOrBuilder() {
      return getTargetPosition();
    }

    public static final int INDEX_FIELD_NUMBER = 3;
    private int index_;
    /**
     * <pre>
     * For TRAVEL, DROP, EQUIP, PICKUP
     * </pre>
     *
     * <code>int32 index = 3;</code>
     * @return The index.
     */
    @Override
    public int getIndex() {
      return index_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (decisionType_ != CharacterProtos.DecisionType.NONE.getNumber()) {
        output.writeEnum(1, decisionType_);
      }
      if (targetPosition_ != null) {
        output.writeMessage(2, getTargetPosition());
      }
      if (index_ != 0) {
        output.writeInt32(3, index_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (decisionType_ != CharacterProtos.DecisionType.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, decisionType_);
      }
      if (targetPosition_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTargetPosition());
      }
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, index_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PlayerDecision)) {
        return super.equals(obj);
      }
      PlayerDecision other = (PlayerDecision) obj;

      if (decisionType_ != other.decisionType_) return false;
      if (hasTargetPosition() != other.hasTargetPosition()) return false;
      if (hasTargetPosition()) {
        if (!getTargetPosition()
            .equals(other.getTargetPosition())) return false;
      }
      if (getIndex()
          != other.getIndex()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DECISION_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + decisionType_;
      if (hasTargetPosition()) {
        hash = (37 * hash) + TARGET_POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getTargetPosition().hashCode();
      }
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PlayerDecision parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerDecision parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerDecision parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerDecision parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerDecision parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerDecision parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerDecision parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlayerDecision parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlayerDecision parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PlayerDecision parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlayerDecision parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlayerDecision parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PlayerDecision prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Proto sent from player to engine
     * </pre>
     *
     * Protobuf type {@code player_communication.PlayerDecision}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:player_communication.PlayerDecision)
        PlayerDecisionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlayerProtos.internal_static_player_communication_PlayerDecision_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlayerProtos.internal_static_player_communication_PlayerDecision_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PlayerDecision.class, Builder.class);
      }

      // Construct using mech.mania.engine.domain.model.PlayerProtos.PlayerDecision.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        decisionType_ = 0;

        if (targetPositionBuilder_ == null) {
          targetPosition_ = null;
        } else {
          targetPosition_ = null;
          targetPositionBuilder_ = null;
        }
        index_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlayerProtos.internal_static_player_communication_PlayerDecision_descriptor;
      }

      @Override
      public PlayerDecision getDefaultInstanceForType() {
        return PlayerDecision.getDefaultInstance();
      }

      @Override
      public PlayerDecision build() {
        PlayerDecision result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PlayerDecision buildPartial() {
        PlayerDecision result = new PlayerDecision(this);
        result.decisionType_ = decisionType_;
        if (targetPositionBuilder_ == null) {
          result.targetPosition_ = targetPosition_;
        } else {
          result.targetPosition_ = targetPositionBuilder_.build();
        }
        result.index_ = index_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PlayerDecision) {
          return mergeFrom((PlayerDecision)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PlayerDecision other) {
        if (other == PlayerDecision.getDefaultInstance()) return this;
        if (other.decisionType_ != 0) {
          setDecisionTypeValue(other.getDecisionTypeValue());
        }
        if (other.hasTargetPosition()) {
          mergeTargetPosition(other.getTargetPosition());
        }
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PlayerDecision parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PlayerDecision) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int decisionType_ = 0;
      /**
       * <code>.character.DecisionType decision_type = 1;</code>
       * @return The enum numeric value on the wire for decisionType.
       */
      @Override public int getDecisionTypeValue() {
        return decisionType_;
      }
      /**
       * <code>.character.DecisionType decision_type = 1;</code>
       * @param value The enum numeric value on the wire for decisionType to set.
       * @return This builder for chaining.
       */
      public Builder setDecisionTypeValue(int value) {

        decisionType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.character.DecisionType decision_type = 1;</code>
       * @return The decisionType.
       */
      @Override
      public CharacterProtos.DecisionType getDecisionType() {
        @SuppressWarnings("deprecation")
        CharacterProtos.DecisionType result = CharacterProtos.DecisionType.valueOf(decisionType_);
        return result == null ? CharacterProtos.DecisionType.UNRECOGNIZED : result;
      }
      /**
       * <code>.character.DecisionType decision_type = 1;</code>
       * @param value The decisionType to set.
       * @return This builder for chaining.
       */
      public Builder setDecisionType(CharacterProtos.DecisionType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        decisionType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.character.DecisionType decision_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDecisionType() {

        decisionType_ = 0;
        onChanged();
        return this;
      }

      private CharacterProtos.Position targetPosition_;
      private com.google.protobuf.SingleFieldBuilderV3<
          CharacterProtos.Position, CharacterProtos.Position.Builder, CharacterProtos.PositionOrBuilder> targetPositionBuilder_;
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position target_position = 2;</code>
       * @return Whether the targetPosition field is set.
       */
      public boolean hasTargetPosition() {
        return targetPositionBuilder_ != null || targetPosition_ != null;
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position target_position = 2;</code>
       * @return The targetPosition.
       */
      public CharacterProtos.Position getTargetPosition() {
        if (targetPositionBuilder_ == null) {
          return targetPosition_ == null ? CharacterProtos.Position.getDefaultInstance() : targetPosition_;
        } else {
          return targetPositionBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position target_position = 2;</code>
       */
      public Builder setTargetPosition(CharacterProtos.Position value) {
        if (targetPositionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          targetPosition_ = value;
          onChanged();
        } else {
          targetPositionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position target_position = 2;</code>
       */
      public Builder setTargetPosition(
          CharacterProtos.Position.Builder builderForValue) {
        if (targetPositionBuilder_ == null) {
          targetPosition_ = builderForValue.build();
          onChanged();
        } else {
          targetPositionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position target_position = 2;</code>
       */
      public Builder mergeTargetPosition(CharacterProtos.Position value) {
        if (targetPositionBuilder_ == null) {
          if (targetPosition_ != null) {
            targetPosition_ =
              CharacterProtos.Position.newBuilder(targetPosition_).mergeFrom(value).buildPartial();
          } else {
            targetPosition_ = value;
          }
          onChanged();
        } else {
          targetPositionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position target_position = 2;</code>
       */
      public Builder clearTargetPosition() {
        if (targetPositionBuilder_ == null) {
          targetPosition_ = null;
          onChanged();
        } else {
          targetPosition_ = null;
          targetPositionBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position target_position = 2;</code>
       */
      public CharacterProtos.Position.Builder getTargetPositionBuilder() {

        onChanged();
        return getTargetPositionFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position target_position = 2;</code>
       */
      public CharacterProtos.PositionOrBuilder getTargetPositionOrBuilder() {
        if (targetPositionBuilder_ != null) {
          return targetPositionBuilder_.getMessageOrBuilder();
        } else {
          return targetPosition_ == null ?
              CharacterProtos.Position.getDefaultInstance() : targetPosition_;
        }
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position target_position = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CharacterProtos.Position, CharacterProtos.Position.Builder, CharacterProtos.PositionOrBuilder>
          getTargetPositionFieldBuilder() {
        if (targetPositionBuilder_ == null) {
          targetPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CharacterProtos.Position, CharacterProtos.Position.Builder, CharacterProtos.PositionOrBuilder>(
                  getTargetPosition(),
                  getParentForChildren(),
                  isClean());
          targetPosition_ = null;
        }
        return targetPositionBuilder_;
      }

      private int index_ ;
      /**
       * <pre>
       * For TRAVEL, DROP, EQUIP, PICKUP
       * </pre>
       *
       * <code>int32 index = 3;</code>
       * @return The index.
       */
      @Override
      public int getIndex() {
        return index_;
      }
      /**
       * <pre>
       * For TRAVEL, DROP, EQUIP, PICKUP
       * </pre>
       *
       * <code>int32 index = 3;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {

        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * For TRAVEL, DROP, EQUIP, PICKUP
       * </pre>
       *
       * <code>int32 index = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {

        index_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:player_communication.PlayerDecision)
    }

    // @@protoc_insertion_point(class_scope:player_communication.PlayerDecision)
    private static final PlayerDecision DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlayerDecision();
    }

    public static PlayerDecision getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerDecision>
        PARSER = new com.google.protobuf.AbstractParser<PlayerDecision>() {
      @Override
      public PlayerDecision parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerDecision(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerDecision> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PlayerDecision> getParserForType() {
      return PARSER;
    }

    @Override
    public PlayerDecision getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_player_communication_PlayerTurn_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_player_communication_PlayerTurn_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_player_communication_PlayerDecision_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_player_communication_PlayerDecision_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014player.proto\022\024player_communication\032\020ga" +
      "me_state.proto\032\017character.proto\"L\n\nPlaye" +
      "rTurn\022)\n\ngame_state\030\001 \001(\0132\025.game_state.G" +
      "ameState\022\023\n\013player_name\030\002 \001(\t\"}\n\016PlayerD" +
      "ecision\022.\n\rdecision_type\030\001 \001(\0162\027.charact" +
      "er.DecisionType\022,\n\017target_position\030\002 \001(\013" +
      "2\023.character.Position\022\r\n\005index\030\003 \001(\005B?\n\036" +
      "mech.mania.engine.domain.modelB\014PlayerPr" +
      "otos\252\002\016MM26.IO.Modelsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          GameStateProtos.getDescriptor(),
          CharacterProtos.getDescriptor(),
        });
    internal_static_player_communication_PlayerTurn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_player_communication_PlayerTurn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_player_communication_PlayerTurn_descriptor,
        new String[] { "GameState", "PlayerName", });
    internal_static_player_communication_PlayerDecision_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_player_communication_PlayerDecision_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_player_communication_PlayerDecision_descriptor,
        new String[] { "DecisionType", "TargetPosition", "Index", });
    GameStateProtos.getDescriptor();
    CharacterProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
