// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visualizer.proto

package mech.mania.engine.domain.model;

public final class VisualizerProtos {
  private VisualizerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VisualizerInitialOrBuilder extends
      // @@protoc_insertion_point(interface_extends:player_communication.VisualizerInitial)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.game.GameState state = 1;</code>
     * @return Whether the state field is set.
     */
    boolean hasState();
    /**
     * <code>.game.GameState state = 1;</code>
     * @return The state.
     */
    mech.mania.engine.domain.model.GameStateProtos.GameState getState();
    /**
     * <code>.game.GameState state = 1;</code>
     */
    mech.mania.engine.domain.model.GameStateProtos.GameStateOrBuilder getStateOrBuilder();
  }
  /**
   * Protobuf type {@code player_communication.VisualizerInitial}
   */
  public static final class VisualizerInitial extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:player_communication.VisualizerInitial)
      VisualizerInitialOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VisualizerInitial.newBuilder() to construct.
    private VisualizerInitial(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VisualizerInitial() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VisualizerInitial();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VisualizerInitial(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              mech.mania.engine.domain.model.GameStateProtos.GameState.Builder subBuilder = null;
              if (state_ != null) {
                subBuilder = state_.toBuilder();
              }
              state_ = input.readMessage(mech.mania.engine.domain.model.GameStateProtos.GameState.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(state_);
                state_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mech.mania.engine.domain.model.VisualizerProtos.internal_static_player_communication_VisualizerInitial_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mech.mania.engine.domain.model.VisualizerProtos.internal_static_player_communication_VisualizerInitial_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial.class, mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial.Builder.class);
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private mech.mania.engine.domain.model.GameStateProtos.GameState state_;
    /**
     * <code>.game.GameState state = 1;</code>
     * @return Whether the state field is set.
     */
    @java.lang.Override
    public boolean hasState() {
      return state_ != null;
    }
    /**
     * <code>.game.GameState state = 1;</code>
     * @return The state.
     */
    @java.lang.Override
    public mech.mania.engine.domain.model.GameStateProtos.GameState getState() {
      return state_ == null ? mech.mania.engine.domain.model.GameStateProtos.GameState.getDefaultInstance() : state_;
    }
    /**
     * <code>.game.GameState state = 1;</code>
     */
    @java.lang.Override
    public mech.mania.engine.domain.model.GameStateProtos.GameStateOrBuilder getStateOrBuilder() {
      return getState();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != null) {
        output.writeMessage(1, getState());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getState());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial)) {
        return super.equals(obj);
      }
      mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial other = (mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial) obj;

      if (hasState() != other.hasState()) return false;
      if (hasState()) {
        if (!getState()
            .equals(other.getState())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code player_communication.VisualizerInitial}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:player_communication.VisualizerInitial)
        mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitialOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mech.mania.engine.domain.model.VisualizerProtos.internal_static_player_communication_VisualizerInitial_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mech.mania.engine.domain.model.VisualizerProtos.internal_static_player_communication_VisualizerInitial_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial.class, mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial.Builder.class);
      }

      // Construct using mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (stateBuilder_ == null) {
          state_ = null;
        } else {
          state_ = null;
          stateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mech.mania.engine.domain.model.VisualizerProtos.internal_static_player_communication_VisualizerInitial_descriptor;
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial getDefaultInstanceForType() {
        return mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial.getDefaultInstance();
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial build() {
        mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial buildPartial() {
        mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial result = new mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial(this);
        if (stateBuilder_ == null) {
          result.state_ = state_;
        } else {
          result.state_ = stateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial) {
          return mergeFrom((mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial other) {
        if (other == mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial.getDefaultInstance()) return this;
        if (other.hasState()) {
          mergeState(other.getState());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private mech.mania.engine.domain.model.GameStateProtos.GameState state_;
      private com.google.protobuf.SingleFieldBuilderV3<
          mech.mania.engine.domain.model.GameStateProtos.GameState, mech.mania.engine.domain.model.GameStateProtos.GameState.Builder, mech.mania.engine.domain.model.GameStateProtos.GameStateOrBuilder> stateBuilder_;
      /**
       * <code>.game.GameState state = 1;</code>
       * @return Whether the state field is set.
       */
      public boolean hasState() {
        return stateBuilder_ != null || state_ != null;
      }
      /**
       * <code>.game.GameState state = 1;</code>
       * @return The state.
       */
      public mech.mania.engine.domain.model.GameStateProtos.GameState getState() {
        if (stateBuilder_ == null) {
          return state_ == null ? mech.mania.engine.domain.model.GameStateProtos.GameState.getDefaultInstance() : state_;
        } else {
          return stateBuilder_.getMessage();
        }
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      public Builder setState(mech.mania.engine.domain.model.GameStateProtos.GameState value) {
        if (stateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          state_ = value;
          onChanged();
        } else {
          stateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      public Builder setState(
          mech.mania.engine.domain.model.GameStateProtos.GameState.Builder builderForValue) {
        if (stateBuilder_ == null) {
          state_ = builderForValue.build();
          onChanged();
        } else {
          stateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      public Builder mergeState(mech.mania.engine.domain.model.GameStateProtos.GameState value) {
        if (stateBuilder_ == null) {
          if (state_ != null) {
            state_ =
              mech.mania.engine.domain.model.GameStateProtos.GameState.newBuilder(state_).mergeFrom(value).buildPartial();
          } else {
            state_ = value;
          }
          onChanged();
        } else {
          stateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      public Builder clearState() {
        if (stateBuilder_ == null) {
          state_ = null;
          onChanged();
        } else {
          state_ = null;
          stateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      public mech.mania.engine.domain.model.GameStateProtos.GameState.Builder getStateBuilder() {
        
        onChanged();
        return getStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      public mech.mania.engine.domain.model.GameStateProtos.GameStateOrBuilder getStateOrBuilder() {
        if (stateBuilder_ != null) {
          return stateBuilder_.getMessageOrBuilder();
        } else {
          return state_ == null ?
              mech.mania.engine.domain.model.GameStateProtos.GameState.getDefaultInstance() : state_;
        }
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          mech.mania.engine.domain.model.GameStateProtos.GameState, mech.mania.engine.domain.model.GameStateProtos.GameState.Builder, mech.mania.engine.domain.model.GameStateProtos.GameStateOrBuilder> 
          getStateFieldBuilder() {
        if (stateBuilder_ == null) {
          stateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              mech.mania.engine.domain.model.GameStateProtos.GameState, mech.mania.engine.domain.model.GameStateProtos.GameState.Builder, mech.mania.engine.domain.model.GameStateProtos.GameStateOrBuilder>(
                  getState(),
                  getParentForChildren(),
                  isClean());
          state_ = null;
        }
        return stateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:player_communication.VisualizerInitial)
    }

    // @@protoc_insertion_point(class_scope:player_communication.VisualizerInitial)
    private static final mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial();
    }

    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VisualizerInitial>
        PARSER = new com.google.protobuf.AbstractParser<VisualizerInitial>() {
      @java.lang.Override
      public VisualizerInitial parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VisualizerInitial(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VisualizerInitial> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VisualizerInitial> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mech.mania.engine.domain.model.VisualizerProtos.VisualizerInitial getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VisualizerTurnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:player_communication.VisualizerTurn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.game.GameState state = 1;</code>
     * @return Whether the state field is set.
     */
    boolean hasState();
    /**
     * <code>.game.GameState state = 1;</code>
     * @return The state.
     */
    mech.mania.engine.domain.model.GameStateProtos.GameState getState();
    /**
     * <code>.game.GameState state = 1;</code>
     */
    mech.mania.engine.domain.model.GameStateProtos.GameStateOrBuilder getStateOrBuilder();

    /**
     * <code>.game.GameChange change = 2;</code>
     * @return Whether the change field is set.
     */
    boolean hasChange();
    /**
     * <code>.game.GameChange change = 2;</code>
     * @return The change.
     */
    mech.mania.engine.domain.model.GameStateProtos.GameChange getChange();
    /**
     * <code>.game.GameChange change = 2;</code>
     */
    mech.mania.engine.domain.model.GameStateProtos.GameChangeOrBuilder getChangeOrBuilder();
  }
  /**
   * Protobuf type {@code player_communication.VisualizerTurn}
   */
  public static final class VisualizerTurn extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:player_communication.VisualizerTurn)
      VisualizerTurnOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VisualizerTurn.newBuilder() to construct.
    private VisualizerTurn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VisualizerTurn() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VisualizerTurn();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VisualizerTurn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              mech.mania.engine.domain.model.GameStateProtos.GameState.Builder subBuilder = null;
              if (state_ != null) {
                subBuilder = state_.toBuilder();
              }
              state_ = input.readMessage(mech.mania.engine.domain.model.GameStateProtos.GameState.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(state_);
                state_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              mech.mania.engine.domain.model.GameStateProtos.GameChange.Builder subBuilder = null;
              if (change_ != null) {
                subBuilder = change_.toBuilder();
              }
              change_ = input.readMessage(mech.mania.engine.domain.model.GameStateProtos.GameChange.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(change_);
                change_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mech.mania.engine.domain.model.VisualizerProtos.internal_static_player_communication_VisualizerTurn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mech.mania.engine.domain.model.VisualizerProtos.internal_static_player_communication_VisualizerTurn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn.class, mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn.Builder.class);
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private mech.mania.engine.domain.model.GameStateProtos.GameState state_;
    /**
     * <code>.game.GameState state = 1;</code>
     * @return Whether the state field is set.
     */
    @java.lang.Override
    public boolean hasState() {
      return state_ != null;
    }
    /**
     * <code>.game.GameState state = 1;</code>
     * @return The state.
     */
    @java.lang.Override
    public mech.mania.engine.domain.model.GameStateProtos.GameState getState() {
      return state_ == null ? mech.mania.engine.domain.model.GameStateProtos.GameState.getDefaultInstance() : state_;
    }
    /**
     * <code>.game.GameState state = 1;</code>
     */
    @java.lang.Override
    public mech.mania.engine.domain.model.GameStateProtos.GameStateOrBuilder getStateOrBuilder() {
      return getState();
    }

    public static final int CHANGE_FIELD_NUMBER = 2;
    private mech.mania.engine.domain.model.GameStateProtos.GameChange change_;
    /**
     * <code>.game.GameChange change = 2;</code>
     * @return Whether the change field is set.
     */
    @java.lang.Override
    public boolean hasChange() {
      return change_ != null;
    }
    /**
     * <code>.game.GameChange change = 2;</code>
     * @return The change.
     */
    @java.lang.Override
    public mech.mania.engine.domain.model.GameStateProtos.GameChange getChange() {
      return change_ == null ? mech.mania.engine.domain.model.GameStateProtos.GameChange.getDefaultInstance() : change_;
    }
    /**
     * <code>.game.GameChange change = 2;</code>
     */
    @java.lang.Override
    public mech.mania.engine.domain.model.GameStateProtos.GameChangeOrBuilder getChangeOrBuilder() {
      return getChange();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != null) {
        output.writeMessage(1, getState());
      }
      if (change_ != null) {
        output.writeMessage(2, getChange());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getState());
      }
      if (change_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getChange());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn)) {
        return super.equals(obj);
      }
      mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn other = (mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn) obj;

      if (hasState() != other.hasState()) return false;
      if (hasState()) {
        if (!getState()
            .equals(other.getState())) return false;
      }
      if (hasChange() != other.hasChange()) return false;
      if (hasChange()) {
        if (!getChange()
            .equals(other.getChange())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState().hashCode();
      }
      if (hasChange()) {
        hash = (37 * hash) + CHANGE_FIELD_NUMBER;
        hash = (53 * hash) + getChange().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code player_communication.VisualizerTurn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:player_communication.VisualizerTurn)
        mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mech.mania.engine.domain.model.VisualizerProtos.internal_static_player_communication_VisualizerTurn_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mech.mania.engine.domain.model.VisualizerProtos.internal_static_player_communication_VisualizerTurn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn.class, mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn.Builder.class);
      }

      // Construct using mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (stateBuilder_ == null) {
          state_ = null;
        } else {
          state_ = null;
          stateBuilder_ = null;
        }
        if (changeBuilder_ == null) {
          change_ = null;
        } else {
          change_ = null;
          changeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mech.mania.engine.domain.model.VisualizerProtos.internal_static_player_communication_VisualizerTurn_descriptor;
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn getDefaultInstanceForType() {
        return mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn.getDefaultInstance();
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn build() {
        mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn buildPartial() {
        mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn result = new mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn(this);
        if (stateBuilder_ == null) {
          result.state_ = state_;
        } else {
          result.state_ = stateBuilder_.build();
        }
        if (changeBuilder_ == null) {
          result.change_ = change_;
        } else {
          result.change_ = changeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn) {
          return mergeFrom((mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn other) {
        if (other == mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn.getDefaultInstance()) return this;
        if (other.hasState()) {
          mergeState(other.getState());
        }
        if (other.hasChange()) {
          mergeChange(other.getChange());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private mech.mania.engine.domain.model.GameStateProtos.GameState state_;
      private com.google.protobuf.SingleFieldBuilderV3<
          mech.mania.engine.domain.model.GameStateProtos.GameState, mech.mania.engine.domain.model.GameStateProtos.GameState.Builder, mech.mania.engine.domain.model.GameStateProtos.GameStateOrBuilder> stateBuilder_;
      /**
       * <code>.game.GameState state = 1;</code>
       * @return Whether the state field is set.
       */
      public boolean hasState() {
        return stateBuilder_ != null || state_ != null;
      }
      /**
       * <code>.game.GameState state = 1;</code>
       * @return The state.
       */
      public mech.mania.engine.domain.model.GameStateProtos.GameState getState() {
        if (stateBuilder_ == null) {
          return state_ == null ? mech.mania.engine.domain.model.GameStateProtos.GameState.getDefaultInstance() : state_;
        } else {
          return stateBuilder_.getMessage();
        }
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      public Builder setState(mech.mania.engine.domain.model.GameStateProtos.GameState value) {
        if (stateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          state_ = value;
          onChanged();
        } else {
          stateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      public Builder setState(
          mech.mania.engine.domain.model.GameStateProtos.GameState.Builder builderForValue) {
        if (stateBuilder_ == null) {
          state_ = builderForValue.build();
          onChanged();
        } else {
          stateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      public Builder mergeState(mech.mania.engine.domain.model.GameStateProtos.GameState value) {
        if (stateBuilder_ == null) {
          if (state_ != null) {
            state_ =
              mech.mania.engine.domain.model.GameStateProtos.GameState.newBuilder(state_).mergeFrom(value).buildPartial();
          } else {
            state_ = value;
          }
          onChanged();
        } else {
          stateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      public Builder clearState() {
        if (stateBuilder_ == null) {
          state_ = null;
          onChanged();
        } else {
          state_ = null;
          stateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      public mech.mania.engine.domain.model.GameStateProtos.GameState.Builder getStateBuilder() {
        
        onChanged();
        return getStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      public mech.mania.engine.domain.model.GameStateProtos.GameStateOrBuilder getStateOrBuilder() {
        if (stateBuilder_ != null) {
          return stateBuilder_.getMessageOrBuilder();
        } else {
          return state_ == null ?
              mech.mania.engine.domain.model.GameStateProtos.GameState.getDefaultInstance() : state_;
        }
      }
      /**
       * <code>.game.GameState state = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          mech.mania.engine.domain.model.GameStateProtos.GameState, mech.mania.engine.domain.model.GameStateProtos.GameState.Builder, mech.mania.engine.domain.model.GameStateProtos.GameStateOrBuilder> 
          getStateFieldBuilder() {
        if (stateBuilder_ == null) {
          stateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              mech.mania.engine.domain.model.GameStateProtos.GameState, mech.mania.engine.domain.model.GameStateProtos.GameState.Builder, mech.mania.engine.domain.model.GameStateProtos.GameStateOrBuilder>(
                  getState(),
                  getParentForChildren(),
                  isClean());
          state_ = null;
        }
        return stateBuilder_;
      }

      private mech.mania.engine.domain.model.GameStateProtos.GameChange change_;
      private com.google.protobuf.SingleFieldBuilderV3<
          mech.mania.engine.domain.model.GameStateProtos.GameChange, mech.mania.engine.domain.model.GameStateProtos.GameChange.Builder, mech.mania.engine.domain.model.GameStateProtos.GameChangeOrBuilder> changeBuilder_;
      /**
       * <code>.game.GameChange change = 2;</code>
       * @return Whether the change field is set.
       */
      public boolean hasChange() {
        return changeBuilder_ != null || change_ != null;
      }
      /**
       * <code>.game.GameChange change = 2;</code>
       * @return The change.
       */
      public mech.mania.engine.domain.model.GameStateProtos.GameChange getChange() {
        if (changeBuilder_ == null) {
          return change_ == null ? mech.mania.engine.domain.model.GameStateProtos.GameChange.getDefaultInstance() : change_;
        } else {
          return changeBuilder_.getMessage();
        }
      }
      /**
       * <code>.game.GameChange change = 2;</code>
       */
      public Builder setChange(mech.mania.engine.domain.model.GameStateProtos.GameChange value) {
        if (changeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          change_ = value;
          onChanged();
        } else {
          changeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.game.GameChange change = 2;</code>
       */
      public Builder setChange(
          mech.mania.engine.domain.model.GameStateProtos.GameChange.Builder builderForValue) {
        if (changeBuilder_ == null) {
          change_ = builderForValue.build();
          onChanged();
        } else {
          changeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.game.GameChange change = 2;</code>
       */
      public Builder mergeChange(mech.mania.engine.domain.model.GameStateProtos.GameChange value) {
        if (changeBuilder_ == null) {
          if (change_ != null) {
            change_ =
              mech.mania.engine.domain.model.GameStateProtos.GameChange.newBuilder(change_).mergeFrom(value).buildPartial();
          } else {
            change_ = value;
          }
          onChanged();
        } else {
          changeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.game.GameChange change = 2;</code>
       */
      public Builder clearChange() {
        if (changeBuilder_ == null) {
          change_ = null;
          onChanged();
        } else {
          change_ = null;
          changeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.game.GameChange change = 2;</code>
       */
      public mech.mania.engine.domain.model.GameStateProtos.GameChange.Builder getChangeBuilder() {
        
        onChanged();
        return getChangeFieldBuilder().getBuilder();
      }
      /**
       * <code>.game.GameChange change = 2;</code>
       */
      public mech.mania.engine.domain.model.GameStateProtos.GameChangeOrBuilder getChangeOrBuilder() {
        if (changeBuilder_ != null) {
          return changeBuilder_.getMessageOrBuilder();
        } else {
          return change_ == null ?
              mech.mania.engine.domain.model.GameStateProtos.GameChange.getDefaultInstance() : change_;
        }
      }
      /**
       * <code>.game.GameChange change = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          mech.mania.engine.domain.model.GameStateProtos.GameChange, mech.mania.engine.domain.model.GameStateProtos.GameChange.Builder, mech.mania.engine.domain.model.GameStateProtos.GameChangeOrBuilder> 
          getChangeFieldBuilder() {
        if (changeBuilder_ == null) {
          changeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              mech.mania.engine.domain.model.GameStateProtos.GameChange, mech.mania.engine.domain.model.GameStateProtos.GameChange.Builder, mech.mania.engine.domain.model.GameStateProtos.GameChangeOrBuilder>(
                  getChange(),
                  getParentForChildren(),
                  isClean());
          change_ = null;
        }
        return changeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:player_communication.VisualizerTurn)
    }

    // @@protoc_insertion_point(class_scope:player_communication.VisualizerTurn)
    private static final mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn();
    }

    public static mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VisualizerTurn>
        PARSER = new com.google.protobuf.AbstractParser<VisualizerTurn>() {
      @java.lang.Override
      public VisualizerTurn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VisualizerTurn(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VisualizerTurn> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VisualizerTurn> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mech.mania.engine.domain.model.VisualizerProtos.VisualizerTurn getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_player_communication_VisualizerInitial_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_player_communication_VisualizerInitial_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_player_communication_VisualizerTurn_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_player_communication_VisualizerTurn_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020visualizer.proto\022\024player_communication" +
      "\032\ngame.proto\"3\n\021VisualizerInitial\022\036\n\005sta" +
      "te\030\001 \001(\0132\017.game.GameState\"R\n\016VisualizerT" +
      "urn\022\036\n\005state\030\001 \001(\0132\017.game.GameState\022 \n\006c" +
      "hange\030\002 \001(\0132\020.game.GameChangeBC\n\036mech.ma" +
      "nia.engine.domain.modelB\020VisualizerProto" +
      "s\252\002\016MM26.IO.Modelsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          mech.mania.engine.domain.model.GameStateProtos.getDescriptor(),
        });
    internal_static_player_communication_VisualizerInitial_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_player_communication_VisualizerInitial_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_player_communication_VisualizerInitial_descriptor,
        new java.lang.String[] { "State", });
    internal_static_player_communication_VisualizerTurn_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_player_communication_VisualizerTurn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_player_communication_VisualizerTurn_descriptor,
        new java.lang.String[] { "State", "Change", });
    mech.mania.engine.domain.model.GameStateProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
